version: "3.9"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq  # Имя хоста или адрес RabbitMQ
      - RABBITMQ_PORT=5672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 30M
        reservations:
          cpus: '0.2'
          memory: 10M

    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=56mn40f0
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 47483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 10M
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - app_network
  ###
  pg:
    image: postgres:14.1-alpine
    restart: always
    command: 'postgres'
    volumes:
      - /opt/dev/channel/pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.2'
          memory: 20M
    ports:
      - 25432:5432

networks:
  app_network:
    driver: bridge
